name: Build, test and deploy

on:
  push:
  workflow_dispatch:
    inputs:
      force_build_live_cluster:
        description: "Force live cluster test (yes/no)"
        required: true
        default: "no"

env:
  IMAGE_NAME: gh-actions-test-image
  TAGGED_VERSION_COMMIT: ${{ startsWith(github.ref, 'refs/tags/v') }}
  RUN_LIVE_CLUSTER_TESTS: ${{ github.event.inputs.force_build_live_cluster == 'yes' || env.TAGGED_VERSION_COMMIT }}

jobs:
  test_docker_image:
    runs-on: ubuntu-20.04
    name: Build and test Docker image
    steps:
      - uses: actions/checkout@v2
      - name: Create abc file
        run: |
          echo "$SECRET_FILE_ABC" > abc.txt
        env:
          SECRET_FILE_ABC: ${{ secrets.SECRET_FILE_ABC }}
      - name: Output secret files content
        run: cat secret1.json secret2.txt
      - name: Install NPM dependencies
        run: (cd frontend && npm ci)
      - name: Run frontend unit tests
        run: (cd frontend && npm run test)
      - name: Docker build
        run: docker build --tag "$IMAGE_NAME" .
      - name: Run tests
        if: ${{ !env.RUN_LIVE_CLUSTER_TESTS }}
        run: echo "running tests"
      - name: Run live cluster tests
        if: ${{ env.RUN_LIVE_CLUSTER_TESTS }}
        run: echo "running live tests"
      - name: Docker run
        run: |
          docker run --rm "$IMAGE_NAME" echo "Running docker image"
          docker run --rm "$IMAGE_NAME" echo "Wassup"
      - name: Deploy
        if: env.TAGGED_VERSION_COMMIT
        run: echo "Deploying..."


