name: Workflow

on: push

env:
  IMAGE_NAME: gh-actions-test-image

jobs:
  greetings:
    runs-on: ubuntu-20.04
    steps:
      - name: Send greeting
        run: echo "Hello world"


  test_docker_image:
    runs-on: ubuntu-20.04
    name: Build and test Docker image
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secret files
        run: ./.github/scripts/decrypt_secret_files.sh
        env:
          ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
      - name: Output secret files content
        run: cat secret1.json secret2.txt
      - name: Install NPM dependencies
        run: (cd frontend && npm ci)
      - name: Run frontend unit tests
        run: (cd frontend && npm run test)
      - name: Docker build
        run: docker build --tag "$IMAGE_NAME" .
      - name: Docker run
        run: |
          docker run --rm "$IMAGE_NAME" echo "Running docker image"
          docker run --rm "$IMAGE_NAME" echo "Wassup"
      - name: Deploy
        run: echo "$GITHUB_REF"


