name: Workflow

on:
  push
  workflow_dispatch:
    inputs:
      force_build_live_cluster:
        description: "Force live cluster test (yes/no)"
        required: true
        default: "no"

env:
  IMAGE_NAME: gh-actions-test-image

jobs:
  greetings:
    runs-on: ubuntu-20.04
    steps:
      - name: Send greeting
        run: echo "Hello world"


  test_docker_image:
    runs-on: ubuntu-20.04
    name: Build and test Docker image
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secret files
        run: ./.github/scripts/decrypt_secret_files.sh
        env:
          ENCRYPTION_PASSPHRASE: ${{ secrets.ENCRYPTION_PASSPHRASE }}
      - name: Output secret files content
        run: cat secret1.json secret2.txt
      - name: Install NPM dependencies
        run: (cd frontend && npm ci)
      - name: Run frontend unit tests
        run: (cd frontend && npm run test)
      - name: Docker build
        run: docker build --tag "$IMAGE_NAME" .
      - name: Run tests
        if: github.event.inputs.force_build_live_cluster != 'yes'
        run: echo "running tests"
      - name: Run live cluster tests
        if: github.event.inputs.force_build_live_cluster == 'yes'
        run: echo "running live tests"
      - name: Docker run
        run: |
          docker run --rm "$IMAGE_NAME" echo "Running docker image"
          docker run --rm "$IMAGE_NAME" echo "Wassup"
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "Deploying..."


