name: Workflow

on: push

env:
  IMAGE_NAME: gh-actions-test-image

jobs:
  greetings:
    runs-on: ubuntu-20.04
    steps:
      - name: Send greeting
        run: echo "Hello world"


  build_test_deploy_docker_image:
    runs-on: ubuntu-20.04
    name: Build Docker image
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build --tag "$IMAGE_NAME" .
      - name: Docker run
        run: |
          docker run --rm "$IMAGE_NAME" echo "Running docker image"
          docker run --rm "$IMAGE_NAME" echo "Wassup"


  install_npm_project:
    runs-on: ubuntu-20.04
    name: Install NPM project
    steps:
      - uses: actions/checkout@v2
      - run: (cd frontend && npm ci)

